remote_theme: pmarsceill/just-the-docs

# Auxiliary links for the upper right hand corner
aux_links:
  "Colaboratory Link":
  - "https://colab.research.google.com/notebooks/intro.ipynb"

title: "Pathway Analysis in Python"